name: part_app
description: A new Flutter project.

publish_to: "none"

version: 1.1.11+72

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  firebase_messaging: ^15.0.2
  firebase_remote_config: ^5.0.2
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_calendar_carousel: ^2.4.2
  flutter_flavorizr: ^2.1.4
  flutter_holo_date_picker: ^1.1.0
  flutter_image_compress: ^2.0.3
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.5.4
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.6
  fluttertoast: ^8.0.9
  freezed_annotation: ^2.2.0
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.3
  image_picker: ^1.1.2
  intl: ^0.18.1
  json_annotation: ^4.9.0
  lottie: ^3.1.2
  path_provider: ^2.0.14
  razorpay_flutter: ^1.3.5
  showcaseview: ^3.0.0
  url_launcher: ^6.2.6
  in_app_purchase: ^3.1.11
  share_plus: ^9.0.0
  flutter_native_contact_picker: ^0.0.6
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.7+1

dev_dependencies:
  build_runner: ^2.2.1

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.1
  json_serializable: ^6.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 16 # android min sdk min:16, default 21

flavorizr:
  flavors:
    dev:
      app:
        name: "PartApp"

      android:
        applicationId: "com.part_app.android"

      ios:
        bundleId: "com.partapp.iosx"

    prod:
      app:
        name: "PartApp"

      android:
        applicationId: "com.part_app.android"
      ios:
        bundleId: "com.partapp.iosx"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/
    - assets/images/