// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCphOVhW__jOkGDJvYBAgdoGVuhFHyJUyA',
    appId: '1:174067683059:web:d6b40083033c0def437186',
    messagingSenderId: '174067683059',
    projectId: 'partapp-104d6',
    authDomain: 'partapp-104d6.firebaseapp.com',
    storageBucket: 'partapp-104d6.appspot.com',
    measurementId: 'G-BFNBNYQ3T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJkkKJ06cySRWa2X9n1iW2ah2n4nby7Kw',
    appId: '1:174067683059:android:73184e4bb1f3f383437186',
    messagingSenderId: '174067683059',
    projectId: 'partapp-104d6',
    storageBucket: 'partapp-104d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuxZJKr36WQe0hEY6ssk___S-Sgoa6Zno',
    appId: '1:174067683059:ios:1151076e25fb72e9437186',
    messagingSenderId: '174067683059',
    projectId: 'partapp-104d6',
    storageBucket: 'partapp-104d6.appspot.com',
    iosClientId: '174067683059-seoph6sk0u3oaou8bec51u8624ip6vkf.apps.googleusercontent.com',
    iosBundleId: 'com.partapp.partApp',
  );
}
